### ISSUE TITLE
Ro-Ghoul Auto Farm doesn't work

### ISSUE THREAD

**Issue by go6ko7o** [z4gs/scripts#1]
Hello, when I tested your autofarm for ro-ghoul (it doesn't matter that I am max lvl) it didn't work. The camera bugged out and the menu didn't respond at all.

**Comment by GothHeit** [comment]
That’s probably your injector or maybe even your computer.
For me it works perfectly.

**Comment by go6ko7o** [comment]
It was indeed my injector, thank you!
