### ISSUE TITLE
TRAINER SWITCHING

### ISSUE THREAD

**Issue by MeowFlyx** [z4gs/scripts#5]
![изображение](https://user-images.githubusercontent.com/105730465/169653579-fed394a8-4b3a-448b-a937-9dd799e62a70.png)

I was autofarming on my ccg side (did not tested it on ghoul one), and it was switching the trainer like infinetly, pls fix asap! Ty <3

UPDATE: Also (S1) Koutarou Amon training is broken and does not doing it automatically. Idk about other trainers, except Kureo Mado is working perfect

UPDATE 2: Its not (S1) Koutarou Amon trouble. Its a glitch after failing trainer switching

**Comment by Tanexi** [comment]
u need to switch manually to solve that
just select another trainer,thats all
