### ISSUE TITLE
Game lag on execution

### ISSUE THREAD

**Issue by TheRealPejk** [z4gs/scripts#6]
Me and 3 of my friends using synx and every time we execute the game just freezes and gets like 1 frame every 30 seconds. Wondering if this is a new issue or something. thanks for the great script anyway

**Comment by ySixCx-iTz** [comment]
I use KRNL, and the same thing, so it crashes and I'm kicked from the server, please answer

**Comment by ySixCx-iTz** [comment]
> se você não for retardado saberá que eles corrigiram o script
